In [2]:
import pandas as pd
import matplotlib.pyplot as plt

from datasets import load_dataset
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

pandas.df.sample

return a random sample rows from dataframe

In [3]:
df.sample(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
705072,Business Analyst,Workforce Management Analyst,"Taguig, Metro Manila, Philippines",via Trabajo.org,Full-time,False,Philippines,2023-01-19 03:17:39,False,False,Philippines,None,NaN,NaN,CGI,"['excel', 'word', 'powerpoint']","{'analyst_tools': ['excel', 'word', 'powerpoin..."
187922,Senior Data Scientist,Senior Data science,"Pune, Maharashtra, India",via LinkedIn,Full-time,False,India,2023-01-12 15:14:57,False,False,India,None,NaN,NaN,Careerdimensions,"['sql', 'python', 'aws', 'pyspark', 'flow']","{'cloud': ['aws'], 'libraries': ['pyspark'], '..."
519047,Business Analyst,AI & Business Analyst (Medior/Senior),"Košice, Slovakia",via LinkedIn Slovakia,Full-time and Part-time,False,Slovakia,2023-12-07 11:54:15,False,False,Slovakia,None,NaN,NaN,SCALEUP.agency,"['sql', 'python', 'snowflake', 'excel', 'sheet...","{'analyst_tools': ['excel', 'sheets', 'tableau..."
58627,Data Analyst,Production Operations Database Analyst/Adminis...,Anywhere,via Indeed,Full-time,True,Philippines,2023-08-02 06:38:54,False,False,Philippines,None,NaN,NaN,MicroSourcing,"['sql', 'nosql', 'mongodb', 'mongodb', 'mysql'...","{'cloud': ['oracle', 'azure'], 'databases': ['..."
479716,Business Analyst,Business Analyst,"Teaneck, NJ",via UVeye,Full-time,False,"New York, United States",2023-10-22 14:00:08,False,False,United States,None,NaN,NaN,UVeye,['powerpoint'],{'analyst_tools': ['powerpoint']}
462757,Senior Data Engineer,Senior Data Engineer,Anywhere,via LinkedIn,Full-time,True,Spain,2023-09-12 14:34:46,False,False,Spain,None,NaN,NaN,Optimissa,None,None
403396,Business Analyst,Junior Business Analyst,"Kuala Lumpur, Federal Territory of Kuala Lumpu...",via LinkedIn,None,False,Malaysia,2023-04-03 18:34:35,False,False,Malaysia,None,NaN,NaN,Stampede Solution,None,None
237441,Data Engineer,Sr. Data Engineer,"Georgetown, TX",via BeBee,Full-time and Part-time,False,"New York, United States",2023-12-05 07:05:22,False,True,United States,None,NaN,NaN,Capital One,"['scala', 'sql', 'python', 'java', 'nosql', 'm...","{'cloud': ['aws', 'azure', 'redshift', 'snowfl..."
558442,Data Scientist,Data Scientist,"Vienna, Austria",via BeBee,Full-time,False,Austria,2023-09-12 04:24:00,False,False,Austria,None,NaN,NaN,Reply S.p.A.,"['python', 'r', 'aws', 'azure']","{'cloud': ['aws', 'azure'], 'programming': ['p..."
297081,Data Engineer,"Big Data Engineer Spark, Scala, Python, Pyspark","Dallas, TX",via Dice,Contractor,False,"Texas, United States",2023-03-09 17:10:04,True,False,United States,None,NaN,NaN,"ICS Global Soft, Inc.","['scala', 'python', 'spark', 'pyspark', 'hadoo...","{'libraries': ['spark', 'pyspark', 'hadoop', '..."

In [5]:
df.sample(10, random_state=42)   #random_state=42 → fixes the randomness so you get the same 10 rows every time you run the code

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
502901,Senior Data Engineer,Senior Data Engineer,"St Paul, MN",via BeBee,Full-time,False,"Florida, United States",2023-12-17 11:09:06,False,False,United States,None,NaN,NaN,ManpowerGroup,"['sql', 'azure', 'git']","{'cloud': ['azure'], 'other': ['git'], 'progra..."
406337,Senior Data Scientist,Senior Analytics Engineer,"London, UK",via LinkedIn,Full-time,False,United Kingdom,2023-10-06 16:09:56,False,False,United Kingdom,None,NaN,NaN,Harnham,"['sql', 'python', 'bigquery', 'snowflake', 'lo...","{'analyst_tools': ['looker'], 'cloud': ['bigqu..."
659951,Data Engineer,Data Engineer,"Newcastle upon Tyne, UK",via Indeed,Full-time,False,United Kingdom,2023-09-06 10:11:25,True,False,United Kingdom,None,NaN,NaN,Morgan King,None,None
541593,Data Analyst,Data Analyst,Malta,via Trabajo.org,Full-time,False,Malta,2023-02-14 21:14:18,True,False,Malta,None,NaN,NaN,Konnekt,['jira'],{'async': ['jira']}
425158,Senior Data Engineer,Senior Data Engineer. Job in Amsterdam NBC4i Jobs,"Amsterdam, Netherlands",via NBC4i Jobs,Full-time,False,Netherlands,2023-06-19 16:34:30,True,False,Netherlands,None,NaN,NaN,Independent Recruiters,['python'],{'programming': ['python']}
183426,Data Analyst,Data Analyst,Singapore,via Singapore | JobsDB,Full-time,False,Singapore,2023-11-09 16:07:57,False,False,Singapore,None,NaN,NaN,FLEXOSENSE PTE. LTD.,"['r', 'python', 'java', 'sql', 'sql server', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
287790,Data Analyst,Data Analyst,"Tampa, FL",via LinkedIn,Full-time,False,"Florida, United States",2023-07-14 17:02:23,True,False,United States,None,NaN,NaN,Iris Software Inc.,"['sql', 'hadoop', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['ha..."
541983,Data Analyst,"Data Analyst, Cloud Systems Jobs","Chantilly, VA",via Clearance Jobs,Full-time,False,Georgia,2023-06-15 19:44:34,False,False,United States,None,NaN,NaN,SAIC,"['sql', 'r', 'matlab', 'python', 'oracle', 'aw...","{'analyst_tools': ['power bi', 'tableau', 'qli..."
416896,Data Scientist,Alternant Actuariat & Data Science H/F,France,via LinkedIn,Full-time,False,France,2023-09-22 16:47:24,False,False,France,None,NaN,NaN,KPMG France,None,None
780907,Data Engineer,"Data Engineer with Fivetran,Qlik Must","Mexico City, CDMX, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-16 06:19:09,False,False,Mexico,None,NaN,NaN,CORUS Consulting,"['oracle', 'snowflake', 'aws', 'azure', 'alter...","{'analyst_tools': ['alteryx'], 'cloud': ['orac..."

In [7]:
df.sample(frac=.01)  #1% of the df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
628419,Senior Data Analyst,100% Fully Remote Senior Data Analyst,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-02-13 11:59:59,False,False,United States,None,NaN,NaN,KEYRUS MANAGEMENT COMPANY,"['sql', 'oracle', 'tableau']","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
624241,Business Analyst,Production Engineer,"Pyeongtaek-si, Gyeonggi-do, South Korea",via Trabajo.org - 작업 검색,Full-time,False,South Korea,2023-02-18 12:19:43,True,False,South Korea,None,NaN,NaN,Alfa Laval,None,None
529307,Data Engineer,Sr. Data Engineer,"Fremont, CA",via WANE Jobs,Full-time,False,"Illinois, United States",2023-05-28 19:06:55,False,False,United States,None,NaN,NaN,Supernal,"['sql', 'snowflake', 'bigquery', 'aws', 'redsh...","{'cloud': ['snowflake', 'bigquery', 'aws', 're..."
546810,Data Analyst,Entry Level Data Analyst,"Pleasanton, CA",via FOX21News Jobs,Full-time,False,"California, United States",2023-05-29 19:00:30,False,False,United States,None,NaN,NaN,"Flexon Technologies, INC.",None,None
532846,Senior Data Analyst,Senior Big Data Analyst / PM. Job in Wilmingto...,"Wilmington, DE",via My Valley Jobs Today,Full-time,False,"New York, United States",2023-09-09 19:00:12,True,True,United States,None,NaN,NaN,Kforce,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101141,Data Analyst,Data Analyst,"Rock Island, IL",via Rock Island IL Geebo.com Free Classifieds ...,Full-time,False,"Illinois, United States",2023-01-29 00:02:11,False,True,United States,hour,NaN,24.0,Modis,"['sql', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."
781889,Cloud Engineer,Civil Engineer,"Santiago, Chile","via Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Chile,2023-11-20 06:28:33,False,False,Chile,None,NaN,NaN,CDM Smith,None,None
18245,Senior Data Analyst,Senior Data Analyst - Firm Analytics,"St. Louis, MO",via Jobs Market,Full-time,False,"Illinois, United States",2023-02-28 13:03:17,False,True,United States,None,NaN,NaN,EDWARD JONES,"['sql', 'r', 'sas', 'sas', 'python', 'snowflak...","{'analyst_tools': ['sas', 'spss', 'tableau'], ..."
324128,Data Scientist,Data Scientist H/F,Anywhere,via HelloWork,Full-time,True,France,2023-09-29 17:29:25,False,False,France,None,NaN,NaN,AG2R LA MONDIALE,"['python', 'sql', 'gcp', 'azure', 'docker']","{'cloud': ['gcp', 'azure'], 'other': ['docker'..."
568581,Data Engineer,R&D Data Engineer (R&D Engineer 4),"Los Alamos, NM",via LinkedIn,Full-time,False,"New York, United States",2023-07-25 09:06:57,False,True,United States,None,NaN,NaN,Los Alamos National Laboratory,"['sql', 'python', 'c++', 'java', 'matlab', 'r'...","{'libraries': ['hadoop'], 'os': ['windows', 'l..."

copy-  make a copy of this obj's indices and data

In [ ]:
#df is also updated as df_filled and df_unique when we update any col in df_filled ex- df_filled['job_title'] = df_filled

#df_filled = df  both will be same when updated
#for that we need copy

In [13]:
df_new = df

In [10]:
id(df)

1479559914432

In [14]:
id(df_new)

1479559914432

In [15]:
id(df) == id(df_new)

True

In [16]:
df_original = df.copy()

In [20]:
print(id(df), id(df_original), id(df) == id(df_original))

1479559914432 1479599586288 False

fill nan with median in salary_year_avg col and display 5 rows and see df

In [21]:
median_sal = df_original['salary_year_avg'].median()
df_original['salary_year_avg'] = df_original['salary_year_avg'].fillna(median_sal)
df_original.loc[:5, 'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [23]:
df.loc[:5, 'salary_year_avg']

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: salary_year_avg, dtype: float64